# Generated by Django 4.2.6 on 2023-12-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
